version: '3'
services:

  postgres:
    image: postgres:15.0-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - config/.env
    ports:
      - 5432:5432
    networks:
      - postgres

  backend:
    depends_on:
      - postgres
    build:
      context: .
    env_file:
      - config/.env
    links:
      - postgres:postgres
    command: ["./entrypoint.bash"]
    volumes:
      - ../schema_design/movies_database.ddl:/opt/schema.ddl
      - ../sqlite_to_postgres/:/opt/sqlite_to_postgres/
      - ../postgres_to_es/:/opt/postgres_to_es/
      - static:/static
      - media:/media
    expose:
      - "8000"
    networks:
      - postgres

  nginx:
    image: nginx:1.25.2
    restart: always
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/site/:/etc/nginx/conf.d:ro
      - ./static/:/etc/nginx/data/static/:ro
    depends_on:
      - backend
    ports:
      - 80:80
    networks:
      - postgres

  elasticsearch:
    # container_name: ES
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - http.cors.enabled=true
      - http.cors.allow-origin=/.*/
      - http.cors.allow-origin="https://app.elasticvue.com"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      # - ../postgres_to_es/config/:/usr/share/elasticsearch/config/
      - ../postgres_to_es/config/ES/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    env_file:
      - config/.env
    ports:
      - "9200:9200"
    networks:
      - postgres

  # etl:
  #   restart: always
  #   depends_on:
  #     - elasticsearch
  #   elasticsearch:
  #      condition: service_healthy
  #   env_file:
  #     - ../postgres_to_es/.env
  #   build:
  #     context: ../postgres_to_es
  #   command: ["../postgres_to_es/entrypoint.bash"]
  #   networks:
  #     - postgres


volumes: 
  media:
  static:
  pgdata:
  esdata:
networks:
  postgres:
    driver: bridge